greeting: HELLO PCF !!
encryptedGreeting: '{cipher}AQBMQieCaSbkVfE5YwI5bgTARdcdhs9NpHAuZhXRkHBHMmQjEJIenpcQ5051Lkw6DJIjFc8vJa710ShBXp+cUB0ZvIfgpEAfA3azFlxyCdUr7ffm7mD8dyEyZkeYhGn2DwlVS6XqLC+Q+Juttfnu9JUO447u2Wwyr4Am1w3MoAXveyq2pEpnjtvAS+60kNOugk38H1E4GPHHHqTAqW5Zm3FeQBDw81Ek++KshKFkPyzbL4WkMYppSjq11JCNThpZIG2TsKtqOPVJBy5sGc2eCHD8DDqgL1snIkq7PY4JRP3J+dxM0pePOc/0aJ2FHKaIW2m2C8QR26I2HWtX4aVULzOGmjfxuvyrE+fVrn71Yw50KcOK6etrHIeLGKDXOBENfKSVmDyKcz1zaCs55SAuGnYA'

